version: "3.3"
services:
  proxy:
    image: traefik
    labels:
      - "traefik.frontend.rule=Host:traefik.svc.normiefree.zone"
      - "traefik.port=8080"
      - "traefik.backend=traefik"
      - "traefik.frontend.entryPoints=http"
    configs:
      - source: traefik_config
        target: /etc/traefik/traefik.toml
    volumes:
      - acme:/etc/traefik/acme
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      web_gw:
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    deploy:
      mode: global
      placement:
        constraints:
          - node.role == manager
      update_config:
        parallelism: 1
        delay: 10s

volumes:
  acme:

networks:
  web_gw:
    external:
      name: web_gw
  
configs:
  traefik_config:
    external:
      name: traefik_config