# normiefree.zone | traefik-stack / traefik.toml
# Global configuration for the Traefik reverse proxy Docker Swarm stack.
# John Lettman <the@johnlettman.com>

defaultEntryPoints = ["http", "https"]

[entryPoints]
  [entryPoints.http]
  address = ":80"
   [entryPoints.http.redirect]
   entryPoint = "https"
 [entryPoints.https]
 address = ":443"
   [entryPoints.https.tls]

[acme]
  email       = "admin@normiefree.zone"
  storageFile = "/etc/traefik/acme/acme.json"
  entryPoint  = "https"
  OnHostRule  = true
  onDemand    = true

[acme.httpChallenge]
  entryPoint  = "http"

[web]
  address     = ":8080"

[docker]
  endpoint         = "unix:///var/run/docker.sock"
  domain           = "svc.normiefree.zone"
  watch            = true
  exposedbydefault = false
  swarmmode        = true